language: java
jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - secure: "WqFdF9f4n45hzuYxYufIMZ3+CeVdDf1zIK1M3R8WHQFixszdQGS/JhQMiUdzd//jzpwSx4SnkJZSxxidVPGKNBCtBG9OBdIPza580EntYHqlcG6EfBfwNuym5rcXBOb355Rg8wODsQAL3Sujh1DxY9tfwthrAM5Q8DccwILwWOWLwzI3jNtkzrGi1TasULnG9myKdMjBKT9nGbHciwD0VN2eely0JdC4nq7Ux03sr3BhEKXlxkf3HWnEEdS7VJ3dO3yRohaVSvGJRU+jzfcl7Ac4/NSnz87VAqlu6h6Xzij8GGFLWQBj4YOW2QOTvM3kkh3bEqCA77R17T1lvL1EFVDhTjS6pRcZ5ofObJmN37QBsQXtkZryw6O1sxHuoZ3oJl84QVr8r7LpUOjafqJlvsUwvbcUep0bx0rAFR/4dby/SI3AkLOPPx7sFXIgQHmSeC5DzcpJUebdj78WxVyZsr7MNs7i99fJyn70TchOOpYSbJff2HseQxk8APMHsuYd6/9vGv8Xx3rs2PeXvtWepbOVG3hcb2MfAnPfmXSX2cw0gVMFwpYX8jlpYRdQug27/Kw2xVSjgV2CRUVUcyogz+ULv5KsUvvi5ad8LoLYr5wRVnsxWZYg+C4cblFWfpPGavcIbEmh3Z+Py6+IBFaDmHpjyfQzN8hvz6rcHgVrhUI="

addons:
  sonarcloud:
    organization: "smart-home-oss"
    token:
      secure: $SONAR_KEY_SECURE

script: mvn verify sonar:sonar -q