version: '3'

services:
  user:
    image: smart-home-oss/user-manager:latest
    container_name: user-manager-um-shoss
    build:
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=Host(`user.localhost`)"
      - "traefik.http.routers.user.entrypoints=web"
    ports:
      - 7001:7001

networks:
  smarthomeoss:
    external: true