version: '3'

services:
  user:
    image: smart-home-oss/user-manager:latest
    container_name: user-manager-um-shoss
    build:
      dockerfile: Dockerfile
    environment:
      OAUTH_CLIENT_ID: user-manager
      OAUTH_CLIENT_PASSWORD: qqqqq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=Host(`user.localhost`)"
      - "traefik.http.routers.user.entrypoints=web"

networks:
  smarthomeoss:
    external: true