@startuml
actor Alice
control "User Manager" as user_manager
control "Keycloak (Oauth2 Provider)" as oauth2

Alice -> user_manager: access {page}
user_manager --> Alice: redirect to auth page
Alice -> oauth2: login form: user + password
oauth2 --> oauth2: authenticate
oauth2 --> Alice: redirect to {user_manager_host}/login/{temp_token}&&{page}
Alice -> user_manager: access the redirected page
user_manager -> oauth2: validate the {temp_token}
oauth2 --> user_manager: JWT token + refresh token
user_manager --> user_manager: generate JSESSIONID and map to JWT token
user_manager --> Alice: {page} + Cookie=JSESSIONID

@enduml