@startuml
actor Alice
control "user-manager" as user
control "house-manager" as house
control "Oauth2 Provider" as oauth2

Alice -> oauth2: POST user/login
oauth2 --> Alice: return jwt token
Alice -> house: show homes, header=Authentication: Bearer qsdqsdqsdqsdq...
house -> oauth2: validate jwt token
oauth2 --> house: ok
house --> Alice: list of homes + JSESSIONID

@enduml